### PR TITLE
Update project to work with Django 1.7

### PR DESCRIPTION
**Pull request by danielsamuels**

### CODE REVIEW

**Comment by etianen** [comment]
Have you tested these changes in production yet? As in, am I good to push out a release.

**Comment by danielsamuels** [comment]
Not tested in production, migrations work fine locally though.

**Comment by etianen** [comment]
Cool. I’ll push this out tomorrow morning.

**Comment by danielsamuels** [comment]
Great. You'll likely see a PR for 1.8 in the next week or so too.

**Comment by etianen** [comment]
1.0.4 has landed. :)

**Pull request merged**
