### PR TITLE
PEP8 fixes and Python 3 compatibility

### PR DESCRIPTION
**Pull request by danielsamuels**
This pull request adds Python 3 compatibility and also brings the code style up-to-date with PEP8 guidelines.

The library is used in our CMS tests which run against the following matrix:

Python version | Django version
--- | ---
2.7 | 1.7.8
2.7 | 1.8.2
3.3 | 1.7.8
3.3 | 1.8.2
3.4 | 1.7.8
3.4 | 1.8.2
pypy | 1.7.8
pypy | 1.8.2

[This build](https://travis-ci.org/onespacemedia/cms/builds/65397055) passed fully. The tests in the historylinks project are also passing.

### CODE REVIEW

**Comment by etianen** [comment]
What did you use for the PEP8 linting, btw?

**Comment by danielsamuels** [comment]
I'm using AutoPEP8 in Sublime with the max line length option disabled.

**Comment by etianen** [comment]
Lovely jubbly, thanks.

**Comment by danielsamuels** [comment]
Do you know when you might be able to issue a new release? We're currently blocked for Python 3 compatibility and would like to issue a new version.

**Comment by etianen** [comment]
How about right now?

**Comment by danielsamuels** [comment]
Perfect, thanks!

**Pull request merged**
